# 実践問題

In [22]:
import numpy as np
import pandas as pd

In [24]:
factor_dict = pd.read_csv('要因.csv', index_col=0).to_dict()['CAUSE']

In [158]:
factor_dict[1]

'Unknown'

In [25]:
df = pd.read_csv('test1.csv')
df

        start        end     nr serial  error_code factor  print_count
0    2020/1/1   2020/1/2  500-1    aaa           1     PQ            1
1    2020/1/2   2020/1/7  500-2    aaa           2     PQ            2
2    2020/1/3   2020/2/7  500-3    aaa           4    JAM            3
3    2020/1/4  2020/1/10  600-1    aaa           8     PQ            4
4    2020/1/5  2020/2/20  600-1    aaa           3  Noise            5
5    2020/1/6  2020/3/20  600-1    aaa           2  Noise            6
6    2020/1/7   2020/1/7  701-1    bbb           4    JAM            7
7    2020/1/8   2020/1/2  500-1    bbb           8     PQ            8
8    2020/1/9   2020/1/7  500-2    bbb           1    JAM            9
9   2020/1/10   2020/2/7  500-3    bbb           2    JAM           10
10  2020/1/11  2020/1/10  600-1    bbb        7392     PQ           11
11  2020/1/12  2020/2/20  600-1    bbb           8  Noise           12
12  2020/1/13  2020/3/20  600-1    bbb           1  Noise           13
13  2020/1/14   2020/1/7  701-1    bbb           2    JAM           14
14  2020/1/15   2020/1/7  801-1    bbb           4    JAM           15
15  2020/1/16   2020/1/7  801-1    ccc           8    JAM           16
16  2020/1/17   2020/1/7  801-1    ccc           1    JAM           17

In [ ]:
df.loc[]

In [6]:
deviceid_list = df.serial.unique()
deviceid_list

array(['aaa', 'bbb', 'ccc'], dtype=object)

In [13]:
n = round(len(deviceid_list)/2)

for i in range(0, len(deviceid_list), n):
    device = deviceid_list[i: i+n]
    _df = df[df.serial.isin(device)]
    print(i,_df)

0         start        end     nr serial  error_code factor  print_count
0    2020/1/1   2020/1/2  500-1    aaa           1     PQ            1
1    2020/1/2   2020/1/7  500-2    aaa           2     PQ            2
2    2020/1/3   2020/2/7  500-3    aaa           4    JAM            3
3    2020/1/4  2020/1/10  600-1    aaa           8     PQ            4
4    2020/1/5  2020/2/20  600-1    aaa           3  Noise            5
5    2020/1/6  2020/3/20  600-1    aaa           2  Noise            6
6    2020/1/7   2020/1/7  701-1    bbb           4    JAM            7
7    2020/1/8   2020/1/2  500-1    bbb           8     PQ            8
8    2020/1/9   2020/1/7  500-2    bbb           1    JAM            9
9   2020/1/10   2020/2/7  500-3    bbb           2    JAM           10
10  2020/1/11  2020/1/10  600-1    bbb        7392     PQ           11
11  2020/1/12  2020/2/20  600-1    bbb           8  Noise           12
12  2020/1/13  2020/3/20  600-1    bbb           1  Noise           13
13  2020/1/14   2020/1/7  701-1    bbb           2    JAM           14
14  2020/1/15   2020/1/7  801-1    bbb           4    JAM           15
2         start       end     nr serial  error_code factor  print_count
15  2020/1/16  2020/1/7  801-1    ccc           8    JAM           16
16  2020/1/17  2020/1/7  801-1    ccc           1    JAM           17

In [21]:
for i in range(0, 3, 2):
    print(i)

0
2

In [ ]:
# Yahoo!ニュースのトピック一覧ページからタイトルとカテゴリを取得

import requests
from bs4 import BeautifulSoup
import pandas as pd

def get_titles_and_categories(url):
    # URLにアクセスしてページのHTMLを取得
    response = requests.get(url)
    soup = BeautifulSoup(response.content, 'html.parser')
    
    # 各カテゴリーとその記事タイトルを抽出
    sections = soup.find_all('div', class_='sc-hwj2au-1')
    data = []

    for section in sections:
        category = section.find('a').get_text(strip=True)
        articles = section.find_all('li', class_='sc-1nhdoj2-0')
        for article in articles:
            title = article.find('a').get_text(strip=True)
            data.append({"Category": category, "Title": title})
    
    return data

# Yahoo!ニュースのトピック一覧ページからタイトルとカテゴリを取得
url = "https://news.yahoo.co.jp/topics"
data = get_titles_and_categories(url)

# データをデータフレームに変換
df = pd.DataFrame(data)

# データフレームをCSVファイルに保存
df.to_csv('news_titles_and_categories.csv', index=False, encoding='utf-8-sig')

print("カテゴリと記事タイトルがnews_titles_and_categories.csvに保存されました。")

カテゴリと記事タイトルがnews_titles_and_categories.csvに保存されました。

In [ ]:
以下のサイトから、一ヶ月以内に更新された「製品・ソリューション」の情報のみを取得するPythonのコードを教えてください。
情報がある場合は、pandasを用いて、csvファイルで出力してください。
コメントは日本語で書いてください。
https://www.kyoceradocumentsolutions.com/ja/news/rls_2024/

一つの記事は、以下のような構成です。
この記事の場合は、2024/12/09が更新日で、「製品・ソリューション」の情報です。
<li>
                        <div class="news-entries__date">2024/12/09</div>
                        <div class="news-entries__category">
                            <a href="/ja/news/products-solutions/">製品・ソリューション</a>
                        </div>
                        <div class="news-entries__title"><a href="/ja/news/rls_2024/rls_20241209.html">カラーA4プリンターECOSYS PA2600cwx、カラーA4複合機ECOSYS MA2600cwfxを新発売</a></div>
                    </li>

In [11]:
# ニュースサイトから、一ヶ月以内の記事を取得する

import requests
from bs4 import BeautifulSoup
import pandas as pd
from datetime import datetime, timedelta

# 基本URLを設定します
base_url = "https://www.kyoceradocumentsolutions.com"

# ニュースのURLを設定します
news_url = "https://www.kyoceradocumentsolutions.com/ja/news/rls_2024/"

# ページを取得します
response = requests.get(news_url)
soup = BeautifulSoup(response.text, "html.parser")

# 現在の日付を取得します
now = datetime.now()
one_month_ago = now - timedelta(days=40)

# データを格納するリストを準備します
data = []

# ニュースエントリーをすべて抽出します
entries = soup.find_all("li")
for entry in entries:
    date_div = entry.find("div", class_="news-entries__date")
    category_div = entry.find("div", class_="news-entries__category")
    title_div = entry.find("div", class_="news-entries__title")
    
    # 必要な要素がすべて存在するか確認します
    if date_div and category_div and title_div:
        date_str = date_div.text.strip()
        category = category_div.text.strip()
        title = title_div.text.strip()
        relative_link = title_div.find("a")["href"]
        full_link = base_url + relative_link  # フルパスに変換
        
        # 日付をdatetimeオブジェクトに変換します
        entry_date = datetime.strptime(date_str, "%Y/%m/%d")
        
        # カテゴリが「製品・ソリューション」であり、かつ一ヶ月以内に更新された記事のみを抽出します
        if category == "製品・ソリューション" and entry_date >= one_month_ago:
            data.append([entry_date, category, title, full_link])

# pandasのDataFrameを作成します
df = pd.DataFrame(data, columns=["日付", "カテゴリ", "タイトル", "リンク"])

# DataFrameをcsvファイルに出力します
df.to_csv("products_solutions_updates.csv", index=False, encoding="utf-8")

print("CSVファイルに出力しました")

CSVファイルに出力しました

In [9]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
import time
import pandas as pd

# Safari WebDriverを設定します
driver = webdriver.Safari()

# 指定されたURLにアクセスします
driver.get("https://scraping-for-beginner.herokuapp.com/login_page")

# ユーザ名とパスワードを入力します
username = driver.find_element(By.ID, "username")
password = driver.find_element(By.ID, "password")

username.send_keys("imanishi")  # ここに実際のユーザ名を入力してください
password.send_keys("kohei")  # ここに実際のパスワードを入力してください

# ログインボタンをクリックします
login_button = driver.find_element(By.CLASS_NAME, "btn")
login_button.click()

# ログイン後のページが読み込まれるまで少し待機します
time.sleep(5)

# 表を取得します
table = driver.find_element(By.TAG_NAME, "table")

# 表の行データを解析して辞書リストに変換します
rows = table.find_elements(By.TAG_NAME, "tr")
data = []

for row in rows:
    cells = row.find_elements(By.TAG_NAME, "td")
    column_name = row.find_element(By.TAG_NAME, "th").text
    value = cells[0].text if len(cells) > 0 else ""
    data.append({column_name: value})

# DataFrameに変換します
df = pd.DataFrame(data)

# DataFrameを表示します
print(df)

# 必要に応じてCSVファイルに保存します
df.to_csv("mypage_table.csv", index=False)

# ブラウザを閉じます
driver.quit()

     講師名      所属企業        生年月日   出身  \
0  今西 航平       NaN         NaN  NaN
1    NaN  株式会社キカガク         NaN  NaN
2    NaN       NaN  1994年7月15日  NaN
3    NaN       NaN         NaN  千葉県
4    NaN       NaN         NaN  NaN

                                                  趣味
0                                                NaN
1                                                NaN
2                                                NaN
3                                                NaN
4  \n              バスケットボール\n              読書\n  ...

In [ ]:
以下のサイトから、一ヶ月以内に更新されたの情報のみを取得するPythonのコードを教えてください。
情報がある場合は、pandasを用いて、csvファイルで出力してください。
コメントは日本語で書いてください。
https://newsroom.lexmark.com/newsreleases

一つの記事は、以下のような構成です。
この記事の場合は、2025/1/7が更新日で、「Lexmark Named 2025 Leader in LGBTQ+ Workplace Inclusion」の情報です。<li class="wd_item">
<div class="wd_item_wrapper">
	<div class="wd_date">Jan 7, 2025</div>
	<div class="wd_title"><a href="https://newsroom.lexmark.com/2025-01-07-Lexmark-Named-2025-Leader-in-LGBTQ-Workplace-Inclusion">Lexmark Named 2025 Leader in LGBTQ+ Workplace Inclusion</a></div>
	
	<div class="wd_summary"><p>Kentucky-based company has been recognized in Human Rights Campaign Foundation's Corporate Equality Index each year since survey began LEXINGTON, Ky., Jan. 7, 2025 /PRNewswire/ -- Lexmark, a...</p></div>
	
	
</div>
</li>

In [16]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
from datetime import datetime, timedelta

# 現在の日付を取得します
current_date = datetime.now()

# サイトのURL
url = "https://newsroom.lexmark.com/newsreleases"

# リクエストを送信してHTMLを取得します
response = requests.get(url)
soup = BeautifulSoup(response.content, "html.parser")

# ニュース記事を取得します
articles = soup.find_all("li", class_="wd_item")

# データを格納するリスト
data = []

# 各記事を解析します
for article in articles:
    date_str = article.find("div", class_="wd_date").text.strip()
    date = datetime.strptime(date_str, "%b %d, %Y")
    title = article.find("div", class_="wd_title").text.strip()
    summary = article.find("div", class_="wd_summary").text.strip()
    
    # 更新日が一ヶ月以内かどうかを確認します
    if (current_date - date) <= timedelta(days=30):
        data.append({
            "更新日": date_str,
            "タイトル": title,
            "概要": summary
        })

# データをDataFrameに変換します
df = pd.DataFrame(data)

# CSVファイルに保存します
df.to_csv("recent_articles.csv", index=False)

print("CSVファイルが生成されました。")

CSVファイルが生成されました。

In [ ]:
以下の #要件 を満たすPython のコードを作成してください。
#前程条件：
・特定のフォルダ内に複数のcsvファイルがある

#要件：
・ライブラリは、tkinterを使用する
・任意のキーワードを入力すると、そのキーワードが文字内部に含まれるcsvファイルを検索する
・検索フォルダは、pythonファイルと同じフォルダ内とする
・検索する文字列は、部分一致でも可として、大文字と小文字は区別しない
・複数の検索結果があるときには、すべて表示する
・検索された「csvファイル名」と「検索されたセル内の文字列全体」を表形式で表示する
・表示されたファイル名をクリックした場合、csvファイルが開くことができる
・検索のステータスバーを表示する
・GUIのデフォルトサイズは800×800とする

In [ ]:
import os
import csv
import tkinter as tk
from tkinter import filedialog, messagebox
from tkinter import ttk

# キーワードでCSVファイルを検索する関数
def search_csv_files(keyword):
    results = []
    keyword = keyword.lower()
    for file in os.listdir('.'):
        if file.endswith('.csv'):
            with open(file, newline='', encoding='utf-8') as csvfile:
                reader = csv.reader(csvfile)
                for row in reader:
                    for cell in row:
                        if keyword in cell.lower():
                            results.append((file, cell))
                            break
    return results

# 検索ボタンがクリックされたときに呼び出される関数
def on_search():
    keyword = keyword_entry.get()
    if not keyword:
        messagebox.showwarning("入力エラー", "キーワードを入力してください")
        return

    status_label.config(text="検索中...")
    root.update_idletasks()

    results = search_csv_files(keyword)
    for row in tree.get_children():
        tree.delete(row)

    if results:
        for file, cell in results:
            tree.insert("", "end", values=(file, cell))
    else:
        messagebox.showinfo("結果なし", "該当するCSVファイルが見つかりませんでした")

    status_label.config(text="検索完了")

# CSVファイルを開く関数
def open_csv_file(event):
    item = tree.identify('item', event.x, event.y)
    if not item:
        return

    file = tree.item(item, 'values')[0]
    os.startfile(file)

# GUIのセットアップ
root = tk.Tk()
root.title("CSVファイル検索")
root.geometry("800x800")

frame = ttk.Frame(root)
frame.pack(padx=10, pady=10, fill="x", expand=True)

keyword_label = ttk.Label(frame, text="キーワード:")
keyword_label.pack(side="left", padx=(0, 10))

keyword_entry = ttk.Entry(frame)
keyword_entry.pack(side="left", fill="x", expand=True)

search_button = ttk.Button(frame, text="検索", command=on_search)
search_button.pack(side="left", padx=(10, 0))

tree = ttk.Treeview(root, columns=("ファイル名", "内容"), show="headings")
tree.heading("ファイル名", text="ファイル名")
tree.heading("内容", text="内容")
tree.pack(padx=10, pady=10, fill="both", expand=True)

tree.bind("<Double-1>", open_csv_file)

status_label = ttk.Label(root, text="ステータスバー")
status_label.pack(side="bottom", fill="x")

root.mainloop()

In [12]:
import spacy
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import VotingClassifier
from sklearn.pipeline import make_pipeline

# spaCyの英語と日本語モデルをロード
nlp_en = spacy.load("en_core_web_sm")
nlp_ja = spacy.load("ja_core_news_sm")

# ニュースのタイトルとカテゴリのサンプルデータ
titles = [
    "最新のスマートウォッチが市場に投入されました",
    "企業の業績が大幅に向上しました",
    "革新的なタブレットが登場",
    "新しいCEOが就任しました",
    "次世代のゲームコンソールが発売されました",
    "会社の株価が急上昇しました",
    "新しいノートパソコンが発表されました",
    "企業の新しい戦略が公開されました",
    "新しいスマートフォンアプリがリリースされました",
    "取締役会のメンバーが変更されました",
    "最新のワイヤレスイヤホンが販売開始されました",
    "大規模なリストラが発表されました",
    "新しい自動車モデルが登場しました",
    "会社の新しい本社ビルが完成しました",
    "新しいスマートホームデバイスが市場に投入されました",
    "企業の年間収益が記録的な数字に達しました"
]
categories = [
    "新製品情報", "会社の重要情報", "新製品情報", "会社の重要情報",
    "新製品情報", "会社の重要情報", "新製品情報", "会社の重要情報",
    "新製品情報", "会社の重要情報", "新製品情報", "会社の重要情報",
    "新製品情報", "会社の重要情報", "新製品情報", "会社の重要情報"
]

# テキストの前処理関数
def preprocess_text(text):
    doc_ja = nlp_ja(text)
    doc_en = nlp_en(text)
    tokens_ja = [token.lemma_ for token in doc_ja if not token.is_stop]
    tokens_en = [token.lemma_ for token in doc_en if not token.is_stop]
    return " ".join(tokens_ja + tokens_en)

# 前処理済みのテキストを取得
preprocessed_titles = [preprocess_text(title) for title in titles]

# ロジスティック回帰とランダムフォレストを使ったアンサンブルモデルの作成
model = make_pipeline(
    TfidfVectorizer(),
    VotingClassifier(
        estimators=[
            ('lr', LogisticRegression(max_iter=1000)),
            ('rf', LogisticRegression(max_iter=1000))
        ],
        voting='soft'
    )
)

# モデルの訓練
model.fit(preprocessed_titles, categories)

# 新しいニュースタイトルの分類
new_titles = [
    "最新のタブレットが登場しました",
    "会社の新しいプロジェクトが始動しました",
    "次世代のスマートフォンが発表されました",
    "新しいCOOが選任されました",
    "音声をリアルタイムで表示する字幕表示システム「CotopatⓇ Mobile」バージョンアップ版を京セラドキュメントソリューションズジャパンより販売開始",
    "カラーA4プリンターECOSYS PA2600cwx、カラーA4複合機ECOSYS MA2600cwfxを新発売",
    "京セラ株式会社 2025年3月期 第3四半期 決算発表"
]
preprocessed_new_titles = [preprocess_text(title) for title in new_titles]
predicted_categories = model.predict(preprocessed_new_titles)

# 分類結果の表示
for title, category in zip(new_titles, predicted_categories):
    print(f"タイトル: {title} => カテゴリ: {category}")

タイトル: 最新のタブレットが登場しました => カテゴリ: 新製品情報
タイトル: 会社の新しいプロジェクトが始動しました => カテゴリ: 会社の重要情報
タイトル: 次世代のスマートフォンが発表されました => カテゴリ: 新製品情報
タイトル: 新しいCOOが選任されました => カテゴリ: 新製品情報
タイトル: 音声をリアルタイムで表示する字幕表示システム「CotopatⓇ Mobile」バージョンアップ版を京セラドキュメントソリューションズジャパンより販売開始 => カテゴリ: 新製品情報
タイトル: カラーA4プリンターECOSYS PA2600cwx、カラーA4複合機ECOSYS MA2600cwfxを新発売 => カテゴリ: 新製品情報
タイトル: 京セラ株式会社 2025年3月期 第3四半期 決算発表 => カテゴリ: 会社の重要情報

In [3]:
import requests
from bs4 import BeautifulSoup
from gensim.summarization import summarize

# URLリスト
urls = ["https://news.yahoo.co.jp/pickup/6544667"]

# 保存するファイル名
output_file = "summary.txt"

with open(output_file, "w", encoding="utf-8") as file:
    for url in urls:
        response = requests.get(url)
        
        if response.status_code == 200:
            soup = BeautifulSoup(response.text, 'html.parser')
            
            # ページの本文を抽出 (例: <p>タグ)
            paragraphs = soup.find_all('p')
            content = " ".join([p.get_text(strip=True) for p in paragraphs])
            
            # 要約を生成
            if content:
                try:
                    summary = summarize(content, word_count=50)  # 要約の単語数を調整
                except ValueError:
                    summary = "要約が生成できませんでした。本文が短すぎるかもしれません。"
            else:
                summary = "本文が見つかりませんでした。"
            
            # 結果を保存
            file.write(f"URL: {url}\n")
            file.write(f"要約:\n{summary}\n\n")
        else:
            file.write(f"URL: {url} の取得に失敗しました。\n\n")

print(f"要約を{output_file}に保存しました！")

ModuleNotFoundError: No module named 'gensim.summarization'

In [3]:
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from bs4 import BeautifulSoup
import pandas as pd
import time

url = "https://www.hp.com/us-en/shop/pdp/hp-color-laserjet-enterprise-6700dn-printer#techSpecs"

options = Options()
options.add_argument("--headless")
driver = webdriver.Chrome(options=options)

print("Loading page...")
driver.get(url)
time.sleep(8)  # JSロード待ち（長めに）

html = driver.page_source
driver.quit()

print("HTML length:", len(html))
soup = BeautifulSoup(html, "html.parser")

data = []

def add(category, spec, value):
    print(f"[ADD] {category} | {spec} | {value}")
    data.append([category.strip(), spec.strip(), value.strip()])

# -------------------------
# 1. カテゴリ（h2/h3）検出
# -------------------------
print("\n=== Detecting categories (h2/h3) ===")
sections = soup.find_all(["section", "div"])
for sec in sections:
    h = sec.find(["h2", "h3"])
    if h:
        print("Category found:", h.get_text(strip=True))

# -------------------------
# 2. table 構造の検出
# -------------------------
print("\n=== Detecting <table> ===")
tables = soup.find_all("table")
print("Number of tables found:", len(tables))

for t in tables:
    print("Table HTML snippet:", str(t)[:200], "...\n")

# -------------------------
# 3. dl 構造の検出
# -------------------------
print("\n=== Detecting <dl> ===")
dls = soup.find_all("dl")
print("Number of dl found:", len(dls))

for d in dls:
    print("DL snippet:", str(d)[:200], "...\n")

# -------------------------
# 4. spec-key / spec-value の検出
# -------------------------
print("\n=== Detecting .spec-key / .spec-value ===")
keys = soup.select(".spec-key")
values = soup.select(".spec-value")
print("Keys:", len(keys), "Values:", len(values))

# -------------------------
# 5. spec-item の検出
# -------------------------
print("\n=== Detecting .spec-item ===")
items = soup.select(".spec-item")
print("spec-item count:", len(items))

# -------------------------
# 6. 実際の抽出処理
# -------------------------
print("\n=== Extracting data ===")

for sec in sections:
    h = sec.find(["h2", "h3"])
    if not h:
        continue
    category = h.get_text(strip=True)

    # table
    for tr in sec.select("table tr"):
        th = tr.find("th")
        td = tr.find("td")
        if th and td:
            add(category, th.get_text(), td.get_text(" ", strip=True))

    # dl
    for dt in sec.find_all("dt"):
        dd = dt.find_next("dd")
        if dd:
            add(category, dt.get_text(), dd.get_text(" ", strip=True))

    # spec-key/value
    keys = sec.select(".spec-key")
    values = sec.select(".spec-value")
    for k, v in zip(keys, values):
        add(category, k.get_text(), v.get_text(" ", strip=True))

    # spec-item
    for item in sec.select(".spec-item"):
        label = item.select_one(".label")
        value = item.select_one(".value")
        if label and value:
            add(category, label.get_text(), value.get_text(" ", strip=True))

df = pd.DataFrame(data, columns=["Category", "Spec", "Value"])
df.to_excel("hp_specs_debug.xlsx", index=False)

print("\nDone.")

Loading page...
HTML length: 185233

=== Detecting categories (h2/h3) ===

=== Detecting <table> ===
Number of tables found: 0

=== Detecting <dl> ===
Number of dl found: 0

=== Detecting .spec-key / .spec-value ===
Keys: 0 Values: 0

=== Detecting .spec-item ===
spec-item count: 0

=== Extracting data ===

Done.

In [ ]:
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
import time

url = "https://www.hp.com/us-en/shop/pdp/hp-color-laserjet-enterprise-6700dn-printer#techSpecs"

options = Options()
options.add_argument("--headless")
driver = webdriver.Chrome(options=options)

print("Loading page...")
driver.get(url)
time.sleep(8)  # JSロード待ち

# Shadow DOM ホストを探す
hosts = driver.find_elements(By.CSS_SELECTOR, "hp-product-specs")
print("hp-product-specs count:", len(hosts))

if len(hosts) == 0:
    print("Shadow DOM host not found")
    driver.quit()
    raise SystemExit

host = hosts[0]

# Shadow DOM を展開
shadow_root = driver.execute_script("return arguments[0].shadowRoot", host)

print("Shadow root:", shadow_root)

# Shadow DOM 内の table を探す
rows = shadow_root.find_elements(By.CSS_SELECTOR, "table tr")
print("rows found:", len(rows))

for r in rows:
    print(r.text)

driver.quit()

iframe count: 0

IndexError: list index out of range

In [7]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

url = "https://www.brother.ca/en/p/hll2460dw"
res = requests.get(url)
soup = BeautifulSoup(res.text, "html.parser")

rows = []

# --- 1) テーブル形式の仕様を抽出 ---
for table in soup.find_all("table"):
    # カテゴリ名（テーブルの直前の見出しを取得）
    heading = table.find_previous(["h2", "h3", "h4"])
    category = heading.get_text(strip=True) if heading else "Unknown"

    for tr in table.find_all("tr"):
        cells = tr.find_all(["td", "th"])
        if len(cells) >= 2:
            spec = cells[0].get_text(" ", strip=True)
            value = cells[1].get_text(" ", strip=True)
            rows.append([category, spec, value])

# --- 2) <dl>（定義リスト）形式の仕様を抽出 ---
for dl in soup.find_all("dl"):
    heading = dl.find_previous(["h2", "h3", "h4"])
    category = heading.get_text(strip=True) if heading else "Unknown"

    dts = dl.find_all("dt")
    dds = dl.find_all("dd")

    for dt, dd in zip(dts, dds):
        spec = dt.get_text(" ", strip=True)
        value = dd.get_text(" ", strip=True)
        rows.append([category, spec, value])

# --- 3) その他の仕様ブロック（div 形式） ---
spec_blocks = soup.select("div.specifications, div.product-specifications")
for block in spec_blocks:
    heading = block.find_previous(["h2", "h3", "h4"])
    category = heading.get_text(strip=True) if heading else "Unknown"

    items = block.find_all("div")
    for item in items:
        parts = item.get_text(" ", strip=True).split(":")
        if len(parts) == 2:
            spec, value = parts
            rows.append([category, spec.strip(), value.strip()])

# DataFrame にまとめる
df = pd.DataFrame(rows, columns=["Category", "Spec", "Value"])
df

,Category,Spec,Value
0,Print,Specifictaion Title,Specification Details
1,Print,First Time to Print,Less than 8.5 Seconds
2,Print,Barcode Printing,No
3,Print,Print Colour,Black & White
4,Print,Secure Print,No
5,Print,Print Technology,Laser
6,Print,Recommended Monthly Print Volume (Up to),2500 pages
7,Print,Functions,Print
8,Print,Print Resolution (max. dpi),Up to 1200 x 1200 dpi
9,Print,Duplex Printing,Yes
10,Print,Max. B&W Print Speed,36 ppm
11,Print,Paper Handling Size - Paper Tray,"Letter,Legal,Executive,A4,Folio,A5,A6,B5,B6"
12,Carton Contents,Specifictaion Title,Specification Details
13,Carton Contents,"Carton Dimensions (W"" x D"" x H"")","17.2"" x 11.1"" x 20.4"""
14,Carton Contents,Carton Contents,"Brother HL-L2460DW, Starter Black Toner Cartri..."
15,Carton Contents,Carton Weight,18.0 lbs.
16,Carton Contents,Specifictaion Title,Specification Details
17,Scan,Specifictaion Title,Specification Details
18,Scan,Duplex Scanning,No
19,Scan,Specifictaion Title,Specification Details
20,Other,Specifictaion Title,Specification Details
21,Other,Media Type(s) - Paper Tray,"Plain,Recycled,Thin,Thick"
22,Other,Unit Weight,15.6 lbs.
23,Other,Standard Interface(s),"Ethernet 10/100,Hi-Speed USB 2.0,Wireless 802...."
24,Other,"Unit Dimensions (W"" x D"" x H"")","14.0"" x 14.2"" x 7.2"""
25,Other,Security Functions,"Enterprise Security (802.1x),IP Filter,Setting..."
26,Other,Warranty,1-Year Limited Warranty
27,Other,Paper Handling Size - Manual Feed,"Custom Sizes (3""-8.5"" W, 4.57""-14"" L)"
28,Other,Interface(s),"USB (1.1 or 2.0),Wireless,Ethernet"
29,Other,Sheet Weight - Manual Feed,16-61 lb
30,Other,Sheet Weight - Paper Tray,16-43 lb (Bond)
31,Hardware Features,Specifictaion Title,Specification Details
32,Hardware Features,Operating System (Compatibility),"LinuxÂ®,Windows ServerÂ® 2012,MacÂ® OS X 14.x,..."
33,Hardware Features,Standard Paper Capacity,250 Sheet Paper Capacity
34,Hardware Features,Max. Monthly Duty Cycle,"35,000 pages"
35,Hardware Features,Connectivity,"Ethernet,Wi-Fi,USB"
36,Hardware Features,Standard Memory,128Mb
37,Hardware Features,CPU (Processor) Speed,600 MHz
38,Hardware Features,ENERGY STAR® Qualified,Yes
39,Hardware Features,LCD Display,1-Line LCD
40,Software Features,Specifictaion Title,Specification Details
41,Software Features,Wireless Standard,Yes
42,Software Features,NFC,No
43,Software Features,Wi-Fi CERTIFIEDâ¢,Yes
44,Software Features,Specifictaion Title,Specification Details
45,Unknown,Model #:,HLL2460DW
46,Drums,Item #:,DR830
47,Drums,Item #:,DR830
48,Toner,Item #:,TN830XL
49,Toner,Item #:,TN830XL
50,Toner,Item #:,TN830
51,Toner,Item #:,TN830
52,Toner,Item #:,TN830XL2PK
53,Toner,Item #:,TN830XL2PK
54,Toner,Pros,No Pros
55,Toner,Cons,No Cons

In [8]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

url = "https://jp.ext.hp.com/printers/business-printers/laserjet/enterprise_5700dn/"
res = requests.get(url)
soup = BeautifulSoup(res.text, "html.parser")

rows = []

# --- 1) 仕様テーブル（<table>）をすべて抽出 ---
for table in soup.find_all("table"):
    # テーブルの直前の見出し（カテゴリ名）を取得
    heading = table.find_previous(["h2", "h3", "h4"])
    category = heading.get_text(strip=True) if heading else "カテゴリ不明"

    for tr in table.find_all("tr"):
        cells = tr.find_all(["td", "th"])
        if len(cells) >= 2:
            spec = cells[0].get_text(" ", strip=True)
            value = cells[1].get_text(" ", strip=True)
            rows.append([category, spec, value])

# --- 2) 定義リスト（<dl><dt><dd>）形式も抽出（HP で使われることがある） ---
for dl in soup.find_all("dl"):
    heading = dl.find_previous(["h2", "h3", "h4"])
    category = heading.get_text(strip=True) if heading else "カテゴリ不明"

    dts = dl.find_all("dt")
    dds = dl.find_all("dd")

    for dt, dd in zip(dts, dds):
        spec = dt.get_text(" ", strip=True)
        value = dd.get_text(" ", strip=True)
        rows.append([category, spec, value])

# --- 3) その他の仕様ブロック（div 形式）も拾う ---
for block in soup.select("div.spec, div.specification, div.hp-spec"):
    heading = block.find_previous(["h2", "h3", "h4"])
    category = heading.get_text(strip=True) if heading else "カテゴリ不明"

    items = block.find_all("div")
    for item in items:
        text = item.get_text(" ", strip=True)
        if ":" in text:
            spec, value = text.split(":", 1)
            rows.append([category, spec.strip(), value.strip()])

# --- DataFrame にまとめる ---
df = pd.DataFrame(rows, columns=["Category", "Spec", "Value"])
df

,Category,Spec,Value
0,TerraJet,削減,
1,TerraJet,,
2,TerraJet,パフォーマンス,
3,TerraJet,,
4,TerraJet,保護,
...,...,...,...
66,ご購入後のご質問と修理受け付け,,0120-742-594
67,HP Color LaserJet Enterprise MFP 5700dn（6QN28A...,印刷仕様 印刷速度（モノクロ） ※1 A4：約 43ページ/分 印刷速度（カラー） ※1 A...,//www.hp.com/go/printerclaims を参照してください。正確な速度は...
68,HP Color LaserJet Enterprise MFP 5700dn（6QN28A...,印刷速度（モノクロ） ※1 A4：約 43ページ/分 印刷速度（カラー） ※1 A4：約 4...,//www.hp.com/go/printerclaims を参照してください。正確な速度は...
69,HP Color LaserJet Enterprise MFP 5700dn（6QN28A...,その他の技術情報 コントロールパネル 4.3インチカラータッチスクリーン 対応OS ※5 M...,100V ～ 127V （±10%）、50 - 60Hz （±3Hz） 消費電力 印刷時平...
70,HP Color LaserJet Enterprise MFP 5700dn（6QN28A...,コントロールパネル 4.3インチカラータッチスクリーン 対応OS ※5 Microsoft®...,100V ～ 127V （±10%）、50 - 60Hz （±3Hz） 消費電力 印刷時平...

In [ ]:

今日は、中計メンバーの皆さんに、技戦推で取り組んでいる製品競争力分析という活動の結果を共有させて頂きます。
この資料は、中計の仕様グループのチャネルに置いてありますので、必要に応じて、見てください。
これから全部で30分くらい話していきますので、質問があれば、随時止めてください。
技戦推のメンバーも沢山きてもらっているので、素朴な疑問とかでも全然良いです。
この会議チャットでも良いです。
沢山ご意見頂ければ思いますので、よろしくお願いします。

では、活動の背景から説明していきます。
こちらは昨年度、金子上席が、こういった会議で報告した資料の一部になります。
真に価値あるスペックで勝っていても購買に繋がらないケースが増えている、という状況を示しています。
実際、スペックは勝っていても、Copilot に聞くとブラザーのプリンターが勧められる、といった例も示されています。 
こうした状況から、自社製品の強み・弱みをより明確にすることが求められるようになりました。 
そこで今年、第二技戦推として製品競争力分析をスタートしました。

具体的な取り組みとしては、
販売実績や、製品の仕様や技術を多面的に分析し、
戦略に繋がる提案をインプットしていく取り組みになります。
本日は、この部分になっております。

分析手法としては、こういった横並び表を作成しています。
売れ筋モデルを抽出し、様々な項目ごとに、モデルの勝ち負けを比較します。
フォーカス項目を選び、改善提案を考えていく、と言う流れになります。

分析結果をまとめて、１提案１スライドにして報告していくという活動になっています。

日程としては、セグメントごとに順次分析し、プロアク会議や中計にインプットしています。
本日はこの中計チームへのインプットになります。
以上が、活動の全体像についての説明になりますが、ここまではよろしいでしょうか？
何か質問ありますかね？

ではまず、市場分析になります。
A4カラーの31から45ppmまでの製品を対象にしました。
このセグメントではMFPの比率が高いため、MFPの中から売れ筋Top8のモデルを抽出しました。
2100シリーズの競合になると考えました。
このグラフの中では、下側の領域がProの競合、上側がHeavyの競合になるのではないかイメージを持ちながら、
2100の強みと弱みの抽出を行いました。

説明は省略しますが、
地域別の売上や、地域別に売れてるモデルなども情報がありますので、後ほど見ていただければと思います。

分析手法としても、先ほど説明したので、省略します。

こちらが、2100系の競争力を強化すべき項目としてフォーカスした項目になります。
全部で15個の項目がありますので、これから一つひとつ説明させて頂きます。
競合と比較して2100の弱みと強みを示しています。
★のある項目はProモデルからHeavyになると良化していく項目になります。
すでに分科会等で紹介させていただいたものもありますが、改めて説明させて頂きます。

まずは、本体寿命になります。
競合との比較や使われ方からみると、180K程度まで向上させたい、という提案になります。
本体寿命を公開しているメーカーは少ないのですが、ブラザーのみ、200Kを謳っています。
2100のProとHeavyはこのような数値なので、劣っている状態になります。
こちらは、各社の月間平均PVを比較したものになっています。
こちらは2100のPVの分布図です。
ここから、96%のユーザが5年間使えるようになるには180Kの寿命が必要、ということが計算できます。
また、別の結果として、デジブリ技推でP2100を耐久した際に、250Kまで大きな問題がなかった、という結果もあります。
つまり、実質寿命として、まだまだ伸ばせる可能性もあるのではないかと考えました。

続いて、サービス交換性になります。
寿命を伸ばせたとしても、クレーム対応等でサービス交換が必要になってくると思います。
こちらは2100のサービスパーツの出荷率を示しており、定着器は特に市場での交換が多いということが分かります。
2100の交換性を示しており、定着器の交換性をもう少し良くしたほうが良いなと感じました。
ちなみに、ブラザーはユニットの交換性を向上させており、特に定着器の交換性を大幅に向上していきています。
一方、ゼロックスはユニット長寿命化していると思います。
ただし、長寿命化したとしても、クレーム対応等での交換もあるということは忘れてはいけないポイントだと思います。

定着排紙部JAMになります。
先ほど示した市場での定着器交換の理由の一つは、このJAMが原因だと予想しています。
こちらは2100のCSOデータで、定着器の交換要因を示しています。
これを見ると、特に排紙部のJAMが要因で定着器交換になっていることがわかります。
これは、JAM処理性の悪さが影響しているのではないかと推測しました。
2100は、定着、排紙間のパスが外から見えない構成になっています。
口コミを見てみると、紙片がこの空間に残ってしまい、処理できなくなった、というものが複数ありました。
そこで、JAM処理性の悪さが全てかはわかりませんが、発生要因となっている排紙部JAMに対する改善が必要だと考えています。

対応坪量になります。
品質規格は現状のまま、カタログ値を向上させたい、という提案になります。
競合と比較すると2100はCSTとMPの対応坪量で劣っているとわかります。
しかし、実力はもっと高いはずです。
カタログ値でも、グロス紙だけは200gを保証しています。
また、評価でもSH199gはマージンが確認できているようです。
つまり、実力に合わせて、もっとカタログ値は上げられる可能性があると考えています。
事実、2200でそのような対応が行われています。
品質規格が163gですが、220gまでHP責任で向上させいます。
これと同じような考えで、2100もカタログを上げていくことができるのではないと考えています。

給紙オプションになります。
こちらは、カタログ値で負けないためには3段だが、使われ方から見ると、２段で十分なのではないか、という提案になります。
給紙オプションの段数を見ると、2100は1段、Heavyは２段ですが、Xerox C415が3段まで対応しています。
2100で3段まで必要なのかを考察してみました。
まず2100の平均PVは730枚しかありません。
また2200の使われ方をEALで確認しました。
2200においても、3段まで使用しているのは4%のみでした。
使用する紙サイズの種類が、4種類以上使う人は0.1%以下でした。
使われ方から見ると、2段までで十分なのではないかと考えました。

スリープ電力とTEC値になります。
こちらは、スリープ電力とTEC値を更に低下させ、環境対応をアピールしてほしい、という提案になります。
競合とTEC値を比較すると、2100は低めではあるものの、京セラとリコーに見劣りしています。
TEC値の内訳で見ると、キャノン要因部分は変わらないものの、スリープに関するHP要因部分で劣っていることが分かります。
TEC値が優れている京セラとリコーは、ホームページで環境対応のアピールに使っています。
なので、自社もこの部分をHPにもう少し下げてもらい、環境対応をアピールに繋げてほしいと思います。

コピー画質になります。
こちらは、コピー画質とFCOTを両立させたい、という提案になります。
2100Proのコピー画質は競合と比較して、見劣りしています。
こちらが拡大したものになっており、ゼロックスやキヤノンモデルとも見劣りしていることがわかると思います。
Bestモードという高画質モードにすると、画質は改善されされてきます。
しかしFCOTが遅くなってしまいます。
Canonモデルは画質とFCOTの両立ができているので、hpモデルも改善してほしいという内容になります。

小サイズ紙と大サイズ紙のミックスプリントになります。
こちらは切り替え時の本体停止時間をミニマム化したい、という提案になります。
このグラフは、2100と2200のミックスプリント時の時間を比較したものになります。
2100は、A5とA4切り替え時に30秒停止しており、A6とA4では1分停止してしまいます。
この停止時間をミニマム化すべきだと考えています。
また、オペパネ表示にも課題があります。
本体停止時に、最初の2秒間はクーリング表示が出るものの、その後にすぐに消えてしまいます。
そのため、ユーザは何が起こっているか分からないはずです。
なので、少なくとも表示だけでも改善したいと考えています。

使いやすさになります。
ADFの使いやすさを改善したい、という提案になります。
こちらは、カセットの用紙セットや排紙の取り出し易さなど、使いやすさを数値化して比較した結果になっています。
2100をみると、エンジン部の使いやすさは競合と見劣りしないものの、ADFのみ大きく劣っていることが分かります。
2100のhpモデルとデジプリモデルを比較しても、hpモデルのみ劣っているということも分かります。
劣っている部分は、こちらに示しているような項目になっていますが、こうした使いやすさを改善したほうが良いと考えています。
具体的には、こちらに示しているようなもので、原稿トレイのサイズ表示がない、満載表示がない、延長トレイがない、といったことになります。
今後は、使いやすさとデザイン性などのバランスも考慮する必要があるのではないかと考えています。

CPPになります。
2100のCPPは高めであり、レビューサイトでもコストの高さを指摘されている、状況になります。
ブラザー、ゼロックスと比較して、ドラムまで含めたとしても2100のCPPは高い、ということを示しています。
レビューサイトでもコストが高いことが指摘されており、カラーを多く印刷したいなら、お薦めはできない、と直接的に書かれてしまっています。
CPPはビジネス寄りの話だと思いますので、安い方が良いと一概には言えないと思いますが、このように見られています、という情報になります。

これはプロ推の資料になりますが、こんなデータもあります。
右側のグラフで、縦軸が本体価格、横軸がCPPを示しており、ブラザー、ゼロックスより2100のCPPが高いという同じことを示しています。
左側はContにおけるグラフで、CPPが一桁小さい値であることなどが分かります。

ここからは強みの領域になります。

スリーブFPOTになります。
ここは自社が圧倒的に優位なポイントになります。
ODF構成の他社と比較しても、なお自社が優位なポイントになります。
なので、もっとユーザに優位性を訴求してもらいたいと思っています。
もしくは、緩和してコストダウンするという選択肢もあると思います。

両面生産性も同じになります。
自社が圧倒的に優位なポイントになります。
なので、優位性を訴求してもらうか、緩和してコストダウンするという選択肢もあると思います。

実は、グロスの値も圧倒的に優位なポイントになります。
D製品の中でも2100が高い状態です。
緩和してコストダウンするという選択肢もあると思います。

装着同梱に関しても圧倒的に優位なポイントになります。
SCIP3という装着同梱レベルに対応できているのは自社だけになるので、再アピールしてほしいと思っています。

最後、両面対応サイズになります。
折り紙サイズを両面通紙できるのは、2100だけなので、アピールに使えないだろうか？という提案になります。
A5縦、A5横、両方が通紙できるようにしているため、結果としてこういうサイズも流せるという、小型化の強みだと思います。

以上、これらの項目に関して提案させていただきました。
深掘りしたい項目があれば、一緒に検討させて頂きたいと思っています。

補足資料に、他にも分析結果がありますので、気になったら見てもらえればと思います。
報告は以上になります。

ざっと説明したので、質問やご意見等があればお願いします。
ここをもっと深掘りして欲しい、といった要望もあれば、お願いします。

In [ ]:
製品競争力分析 と言う取り組みについて紹介したいと思います。
この活動は二技戦推で今年から新しく始めた活動になります。
今日は、この活動の全体像とプロアク会議で報告した事例を一部紹介していきたいと思います。

■
活動の背景から説明していきます。
こちらは昨年度、金子上席が、こういった会議で報告した資料の一部になります。
真に価値あるスペックで勝っていても購買に繋がらないケースが増えている、という状況を示しています。
実際、スペックは勝っていても、Copilot に聞くとブラザーのプリンターが勧められる、といった例も示されています。 
こうした状況から、自社製品の強み・弱みをより明確にすることが求められるようになりました。 
そこで今年、第二技戦推として製品競争力分析をスタートしました。
ちなみになんですけど、二技戦推の競争力分析の定例の名前はLION会議と名づけていますが、このマークにちなんだものになっています。

■
では、競争力分析について説明します。
販売実績や、製品の仕様や技術を多面的に分析し、戦略に繋がる提案をしていく取り組みになります。
販売実績としては、ポジションを把握した上で、売れ筋モデルを抽出します。
真に価値あるスペック以外も含めた様々な仕様や技術を多面的に分析します。
そして、提案をプロアク会議や中計などにインプットしていくような活動になります。
セグメントごとに、このような取り組みを順番に行なっています。

■
分析手法をもう少し具体的に説明します。
こんな比較表を作っています。
まずは、売れ筋モデルを抽出し、売れている順に並べます。
様々な項目ごとに、モデルの勝ち負けを比較します。
項目としては、150以上の色んな項目があり、二技戦推のメンバーで役割分担して埋めて行っています。
その中からフォーカスする項目を選び、改善提案を考えていく、と言う流れになります。

■
分析には色んなデータソースを使っています。
主要なものは、販売台数、製品スペック、技戦推で実測している性能調査データなどです。
その他にも、課題の抽出や仮説の検証のために、色んなデータを使っています。
特許とか環境の情報は、まだ活用は少なめなので、もっと活用を強化していきたいと思っています。

■
アウトプットとしては、このように結果をまとめて、一提案一スライドにして、報告していくようなものになります。

■
日程になります。
複数のセグメントを順番に進めています。
まず最初はPolstarの領域としてMonoPLE-Hで、トライアルしながら始めました。
その後、ColorSWT、MonoValueを行い、現在MonoOPPを始めているところになります。
それぞれ、プロアク会議で報告してから、チームへインプットしていく、という流れで進めています。

ここまでが、活動の全体像の説明になります。
ここからは、具体的な事例として、カラーSWTセグメントにおける結果の一部を紹介します。

■
市場分析になります。
A4カラーの31から45ppmまでの製品を対象にしました。
このセグメントではMFPの比率が高いため、MFPの中から売れ筋Top8のモデルを抽出しました。
2200と2100がいますが、ここは2100のProとHeavyの競合になると考えました。
このグラフでもう少し細かく見ていくと、価格の低い下側の領域がProの競合、上側がHeavyの競合になると推測しました。
それらも踏まえた上で、2100の強みと弱みの抽出を行いました。

■
こちらが、2100系の競争力を強化すべき項目としてフォーカスした項目になります。
全部で15個の項目があります。
製品寿命、サービス交換性、スリープFPOTなどの項目があります。
弱みと強みになっており、こうした改善提案をしています。
今日は時間の都合上、４つだけ紹介します。

■
まずは、本体寿命になります。
2100は寿命はProが50KでHeavyは120Kになります。
ただし、競合との比較と、使われ方を見ることで、180Kまで向上させた方が良いのではないか？と言う提案になります。
これが仕様の比較で、ブラザーが200Kであり劣っていることが分かります。
こちらが使われ方として、競合機との平均PVの違いも見える状態にしています。
こちらは2100のPVの分布図になっており、使われ方から見ると、180Kの寿命が必要、ということが計算できます。

■
次は、給紙オプションになります。
給紙オプションの段数を見ると、2100は1段、Heavyは２段ですが、Xerox C415が3段まで対応しています。
2100で3段まで必要なのかを考察してみました。
まず2100の平均PVは730枚しかありません。
また2200の使われ方をEALで確認しました。
2200においても、3段まで使用しているのは4%のみでした。
使用する紙サイズの種類が、4種類以上使う人は0.1%以下でした。
使われ方から見ると、Heavyの仕様通り2段までで十分なのではないかと言う提案になります。

■
次は、コピー画質になります。
こちらは、コピー画質とFCOTを両立させたい、という提案になります。
まず2100のコピー画質は競合と比較して、見劣りしています。
こちらが拡大したものになっており、ゼロックスやキヤノンモデルとも見劣りしていることがわかると思います。
Bestモードという高画質モードにすると、画質は改善されされてきます。
しかしFCOTが遅くなってしまいます。
Canonモデルは画質とFCOTの両立ができているので、hpモデルも改善してほしいという内容になります。

■
これまでは弱みでしたが、これは自社の強みとなる、装着同梱になります。
SCIP3という装着同梱レベルに対応できているのは自社だけです。
競合やシッピングロックやシール部材が必要ですが、自社のみがそれがなくできることなので、改めて自社の強みを再アピールしたい、と言う提案になります。

このように、強みや弱みに関して、技戦推視点での改善提案している、と言う取り組みになります。

■
３セグメントでの報告をした中で、頂いたコメントをいくつか抜粋しました。
活動として良い取り組みだと言うコメントを多く頂いています。
また、これはHPに伝えていこう、と言う内容ったものもありますし、
投げ込みや考えるきっかけになったということなど、前向きなコメントを多く頂いています。

■まとめ
まとめになります。
今年から新しく 製品競争力分析 をスタートしました。
試行錯誤しながら進めてきましたが、方向性としては正しかったかと感じています。
今後は提案の質をさらに高めるため、深掘りしていきたいと考えています。
特許戦略や環境戦略などとも連携できると思いますので、ぜひ、相談させて頂きたいと思います。